// Mirrored from mobile app: lib/data/comuni.ts
// No React Native deps — pure data + pure function
// Source of truth: VeloWedding/lib/data/comuni.ts — keep in sync manually

const COMUNI_ITALIANI: { nome: string; provincia: string; regione: string }[] = [
// PIEMONTE
{ nome: 'Torino', provincia: 'TO', regione: 'Piemonte' },
{ nome: 'Novara', provincia: 'NO', regione: 'Piemonte' },
{ nome: 'Cuneo', provincia: 'CN', regione: 'Piemonte' },
{ nome: 'Alessandria', provincia: 'AL', regione: 'Piemonte' },
{ nome: 'Asti', provincia: 'AT', regione: 'Piemonte' },
{ nome: 'Biella', provincia: 'BI', regione: 'Piemonte' },
{ nome: 'Verbania', provincia: 'VB', regione: 'Piemonte' },
{ nome: 'Vercelli', provincia: 'VC', regione: 'Piemonte' },
{ nome: 'Moncalieri', provincia: 'TO', regione: 'Piemonte' },
{ nome: 'Collegno', provincia: 'TO', regione: 'Piemonte' },
{ nome: 'Rivoli', provincia: 'TO', regione: 'Piemonte' },
{ nome: 'Nichelino', provincia: 'TO', regione: 'Piemonte' },
{ nome: 'Chieri', provincia: 'TO', regione: 'Piemonte' },
{ nome: 'Pinerolo', provincia: 'TO', regione: 'Piemonte' },
{ nome: 'Settimo Torinese', provincia: 'TO', regione: 'Piemonte' },
{ nome: 'Alba', provincia: 'CN', regione: 'Piemonte' },
{ nome: 'Bra', provincia: 'CN', regione: 'Piemonte' },
{ nome: 'Fossano', provincia: 'CN', regione: 'Piemonte' },
{ nome: 'Saluzzo', provincia: 'CN', regione: 'Piemonte' },
{ nome: "Monforte d'Alba", provincia: 'CN', regione: 'Piemonte' },
{ nome: 'La Morra', provincia: 'CN', regione: 'Piemonte' },
{ nome: 'Barolo', provincia: 'CN', regione: 'Piemonte' },
{ nome: 'Barbaresco', provincia: 'CN', regione: 'Piemonte' },
{ nome: 'Neive', provincia: 'CN', regione: 'Piemonte' },
{ nome: "Serralunga d'Alba", provincia: 'CN', regione: 'Piemonte' },
{ nome: 'Casale Monferrato', provincia: 'AL', regione: 'Piemonte' },
{ nome: 'Nizza Monferrato', provincia: 'AT', regione: 'Piemonte' },
{ nome: 'Aosta', provincia: 'AO', regione: "Valle d'Aosta" },
{ nome: 'Courmayeur', provincia: 'AO', regione: "Valle d'Aosta" },
// LOMBARDIA
{ nome: 'Milano', provincia: 'MI', regione: 'Lombardia' },
{ nome: 'Brescia', provincia: 'BS', regione: 'Lombardia' },
{ nome: 'Bergamo', provincia: 'BG', regione: 'Lombardia' },
{ nome: 'Monza', provincia: 'MB', regione: 'Lombardia' },
{ nome: 'Como', provincia: 'CO', regione: 'Lombardia' },
{ nome: 'Varese', provincia: 'VA', regione: 'Lombardia' },
{ nome: 'Cremona', provincia: 'CR', regione: 'Lombardia' },
{ nome: 'Pavia', provincia: 'PV', regione: 'Lombardia' },
{ nome: 'Mantova', provincia: 'MN', regione: 'Lombardia' },
{ nome: 'Lecco', provincia: 'LC', regione: 'Lombardia' },
{ nome: 'Lodi', provincia: 'LO', regione: 'Lombardia' },
{ nome: 'Sondrio', provincia: 'SO', regione: 'Lombardia' },
{ nome: 'Desenzano del Garda', provincia: 'BS', regione: 'Lombardia' },
{ nome: 'Bellagio', provincia: 'CO', regione: 'Lombardia' },
{ nome: 'Lenno', provincia: 'CO', regione: 'Lombardia' },
{ nome: 'Cernobbio', provincia: 'CO', regione: 'Lombardia' },
{ nome: 'Tremezzina', provincia: 'CO', regione: 'Lombardia' },
{ nome: 'Varenna', provincia: 'LC', regione: 'Lombardia' },
{ nome: 'Sabbioneta', provincia: 'MN', regione: 'Lombardia' },
// VENETO
{ nome: 'Venezia', provincia: 'VE', regione: 'Veneto' },
{ nome: 'Verona', provincia: 'VR', regione: 'Veneto' },
{ nome: 'Padova', provincia: 'PD', regione: 'Veneto' },
{ nome: 'Vicenza', provincia: 'VI', regione: 'Veneto' },
{ nome: 'Treviso', provincia: 'TV', regione: 'Veneto' },
{ nome: 'Rovigo', provincia: 'RO', regione: 'Veneto' },
{ nome: 'Belluno', provincia: 'BL', regione: 'Veneto' },
{ nome: 'Mestre', provincia: 'VE', regione: 'Veneto' },
{ nome: 'Conegliano', provincia: 'TV', regione: 'Veneto' },
{ nome: 'Bassano del Grappa', provincia: 'VI', regione: 'Veneto' },
{ nome: 'Asolo', provincia: 'TV', regione: 'Veneto' },
{ nome: 'Villafranca di Verona', provincia: 'VR', regione: 'Veneto' },
// TRENTINO-ALTO ADIGE
{ nome: 'Trento', provincia: 'TN', regione: 'Trentino-Alto Adige' },
{ nome: 'Bolzano', provincia: 'BZ', regione: 'Trentino-Alto Adige' },
{ nome: 'Rovereto', provincia: 'TN', regione: 'Trentino-Alto Adige' },
{ nome: 'Merano', provincia: 'BZ', regione: 'Trentino-Alto Adige' },
// FRIULI-VENEZIA GIULIA
{ nome: 'Trieste', provincia: 'TS', regione: 'Friuli-Venezia Giulia' },
{ nome: 'Udine', provincia: 'UD', regione: 'Friuli-Venezia Giulia' },
{ nome: 'Pordenone', provincia: 'PN', regione: 'Friuli-Venezia Giulia' },
// LIGURIA
{ nome: 'Genova', provincia: 'GE', regione: 'Liguria' },
{ nome: 'La Spezia', provincia: 'SP', regione: 'Liguria' },
{ nome: 'Savona', provincia: 'SV', regione: 'Liguria' },
{ nome: 'Imperia', provincia: 'IM', regione: 'Liguria' },
{ nome: 'Sanremo', provincia: 'IM', regione: 'Liguria' },
{ nome: 'Portofino', provincia: 'GE', regione: 'Liguria' },
{ nome: 'Santa Margherita Ligure', provincia: 'GE', regione: 'Liguria' },
{ nome: 'Lerici', provincia: 'SP', regione: 'Liguria' },
{ nome: 'Rapallo', provincia: 'GE', regione: 'Liguria' },
// EMILIA-ROMAGNA
{ nome: 'Bologna', provincia: 'BO', regione: 'Emilia-Romagna' },
{ nome: 'Modena', provincia: 'MO', regione: 'Emilia-Romagna' },
{ nome: 'Parma', provincia: 'PR', regione: 'Emilia-Romagna' },
{ nome: 'Reggio Emilia', provincia: 'RE', regione: 'Emilia-Romagna' },
{ nome: 'Ferrara', provincia: 'FE', regione: 'Emilia-Romagna' },
{ nome: 'Rimini', provincia: 'RN', regione: 'Emilia-Romagna' },
{ nome: 'Forlì', provincia: 'FC', regione: 'Emilia-Romagna' },
{ nome: 'Ravenna', provincia: 'RA', regione: 'Emilia-Romagna' },
{ nome: 'Piacenza', provincia: 'PC', regione: 'Emilia-Romagna' },
{ nome: 'Cesena', provincia: 'FC', regione: 'Emilia-Romagna' },
{ nome: 'Imola', provincia: 'BO', regione: 'Emilia-Romagna' },
// TOSCANA
{ nome: 'Firenze', provincia: 'FI', regione: 'Toscana' },
{ nome: 'Prato', provincia: 'PO', regione: 'Toscana' },
{ nome: 'Livorno', provincia: 'LI', regione: 'Toscana' },
{ nome: 'Siena', provincia: 'SI', regione: 'Toscana' },
{ nome: 'Pisa', provincia: 'PI', regione: 'Toscana' },
{ nome: 'Arezzo', provincia: 'AR', regione: 'Toscana' },
{ nome: 'Pistoia', provincia: 'PT', regione: 'Toscana' },
{ nome: 'Lucca', provincia: 'LU', regione: 'Toscana' },
{ nome: 'Massa', provincia: 'MS', regione: 'Toscana' },
{ nome: 'Grosseto', provincia: 'GR', regione: 'Toscana' },
{ nome: 'Viareggio', provincia: 'LU', regione: 'Toscana' },
{ nome: 'Forte dei Marmi', provincia: 'LU', regione: 'Toscana' },
{ nome: 'Montepulciano', provincia: 'SI', regione: 'Toscana' },
{ nome: 'Montalcino', provincia: 'SI', regione: 'Toscana' },
{ nome: 'San Gimignano', provincia: 'SI', regione: 'Toscana' },
{ nome: 'Volterra', provincia: 'PI', regione: 'Toscana' },
{ nome: 'Cortona', provincia: 'AR', regione: 'Toscana' },
{ nome: 'Pitigliano', provincia: 'GR', regione: 'Toscana' },
{ nome: 'Pienza', provincia: 'SI', regione: 'Toscana' },
{ nome: 'Fiesole', provincia: 'FI', regione: 'Toscana' },
{ nome: 'Castiglione della Pescaia', provincia: 'GR', regione: 'Toscana' },
// MARCHE
{ nome: 'Ancona', provincia: 'AN', regione: 'Marche' },
{ nome: 'Pesaro', provincia: 'PU', regione: 'Marche' },
{ nome: 'Urbino', provincia: 'PU', regione: 'Marche' },
{ nome: 'Macerata', provincia: 'MC', regione: 'Marche' },
{ nome: 'Ascoli Piceno', provincia: 'AP', regione: 'Marche' },
// UMBRIA
{ nome: 'Perugia', provincia: 'PG', regione: 'Umbria' },
{ nome: 'Terni', provincia: 'TR', regione: 'Umbria' },
{ nome: 'Assisi', provincia: 'PG', regione: 'Umbria' },
{ nome: 'Orvieto', provincia: 'TR', regione: 'Umbria' },
{ nome: 'Spoleto', provincia: 'PG', regione: 'Umbria' },
{ nome: 'Gubbio', provincia: 'PG', regione: 'Umbria' },
{ nome: 'Montefalco', provincia: 'PG', regione: 'Umbria' },
// LAZIO
{ nome: 'Roma', provincia: 'RM', regione: 'Lazio' },
{ nome: 'Latina', provincia: 'LT', regione: 'Lazio' },
{ nome: 'Frosinone', provincia: 'FR', regione: 'Lazio' },
{ nome: 'Viterbo', provincia: 'VT', regione: 'Lazio' },
{ nome: 'Tivoli', provincia: 'RM', regione: 'Lazio' },
{ nome: 'Frascati', provincia: 'RM', regione: 'Lazio' },
{ nome: 'Bracciano', provincia: 'RM', regione: 'Lazio' },
{ nome: 'Bolsena', provincia: 'VT', regione: 'Lazio' },
// CAMPANIA
{ nome: 'Napoli', provincia: 'NA', regione: 'Campania' },
{ nome: 'Salerno', provincia: 'SA', regione: 'Campania' },
{ nome: 'Caserta', provincia: 'CE', regione: 'Campania' },
{ nome: 'Sorrento', provincia: 'NA', regione: 'Campania' },
{ nome: 'Positano', provincia: 'SA', regione: 'Campania' },
{ nome: 'Amalfi', provincia: 'SA', regione: 'Campania' },
{ nome: 'Ravello', provincia: 'SA', regione: 'Campania' },
{ nome: 'Praiano', provincia: 'SA', regione: 'Campania' },
{ nome: 'Capri', provincia: 'NA', regione: 'Campania' },
{ nome: 'Ischia', provincia: 'NA', regione: 'Campania' },
{ nome: 'Procida', provincia: 'NA', regione: 'Campania' },
{ nome: 'Pompei', provincia: 'NA', regione: 'Campania' },
// PUGLIA
{ nome: 'Bari', provincia: 'BA', regione: 'Puglia' },
{ nome: 'Taranto', provincia: 'TA', regione: 'Puglia' },
{ nome: 'Foggia', provincia: 'FG', regione: 'Puglia' },
{ nome: 'Lecce', provincia: 'LE', regione: 'Puglia' },
{ nome: 'Brindisi', provincia: 'BR', regione: 'Puglia' },
{ nome: 'Alberobello', provincia: 'BA', regione: 'Puglia' },
{ nome: 'Ostuni', provincia: 'BR', regione: 'Puglia' },
{ nome: 'Otranto', provincia: 'LE', regione: 'Puglia' },
{ nome: 'Gallipoli', provincia: 'LE', regione: 'Puglia' },
{ nome: 'Polignano a Mare', provincia: 'BA', regione: 'Puglia' },
{ nome: 'Locorotondo', provincia: 'BA', regione: 'Puglia' },
{ nome: 'Cisternino', provincia: 'BR', regione: 'Puglia' },
{ nome: 'Fasano', provincia: 'BR', regione: 'Puglia' },
{ nome: 'Vieste', provincia: 'FG', regione: 'Puglia' },
// BASILICATA
{ nome: 'Matera', provincia: 'MT', regione: 'Basilicata' },
{ nome: 'Potenza', provincia: 'PZ', regione: 'Basilicata' },
// CALABRIA
{ nome: 'Reggio Calabria', provincia: 'RC', regione: 'Calabria' },
{ nome: 'Tropea', provincia: 'VV', regione: 'Calabria' },
{ nome: 'Scilla', provincia: 'RC', regione: 'Calabria' },
// SICILIA
{ nome: 'Palermo', provincia: 'PA', regione: 'Sicilia' },
{ nome: 'Catania', provincia: 'CT', regione: 'Sicilia' },
{ nome: 'Messina', provincia: 'ME', regione: 'Sicilia' },
{ nome: 'Siracusa', provincia: 'SR', regione: 'Sicilia' },
{ nome: 'Agrigento', provincia: 'AG', regione: 'Sicilia' },
{ nome: 'Trapani', provincia: 'TP', regione: 'Sicilia' },
{ nome: 'Ragusa', provincia: 'RG', regione: 'Sicilia' },
{ nome: 'Taormina', provincia: 'ME', regione: 'Sicilia' },
{ nome: 'Noto', provincia: 'SR', regione: 'Sicilia' },
{ nome: 'Modica', provincia: 'RG', regione: 'Sicilia' },
{ nome: 'Cefalù', provincia: 'PA', regione: 'Sicilia' },
// SARDEGNA
{ nome: 'Cagliari', provincia: 'CA', regione: 'Sardegna' },
{ nome: 'Sassari', provincia: 'SS', regione: 'Sardegna' },
{ nome: 'Olbia', provincia: 'OT', regione: 'Sardegna' },
{ nome: 'Alghero', provincia: 'SS', regione: 'Sardegna' },
{ nome: 'Porto Cervo', provincia: 'OT', regione: 'Sardegna' },
]

// Provincia → VELO zone — mirrored from mobile app
export const PROVINCIA_TO_VELO_ZONA: Record<string, string> = {
  'TO': 'Langhe & Piemonte', 'CN': 'Langhe & Piemonte', 'AT': 'Langhe & Piemonte',
  'AL': 'Langhe & Piemonte', 'BI': 'Langhe & Piemonte', 'NO': 'Langhe & Piemonte',
  'VC': 'Langhe & Piemonte', 'VB': 'Langhe & Piemonte', 'AO': 'Langhe & Piemonte',
  'PV': 'Langhe & Piemonte',
  'CO': 'Lago di Como', 'LC': 'Lago di Como', 'VA': 'Lago di Como', 'SO': 'Lago di Como',
  'MI': 'Lago di Como', 'MB': 'Lago di Como', 'BG': 'Lago di Como',
  'CR': 'Lago di Como', 'LO': 'Lago di Como',
  'BS': 'Lago di Garda', 'VR': 'Lago di Garda', 'MN': 'Lago di Garda',
  'VE': 'Venezia & Veneto', 'PD': 'Venezia & Veneto', 'VI': 'Venezia & Veneto',
  'TV': 'Venezia & Veneto', 'RO': 'Venezia & Veneto', 'BL': 'Venezia & Veneto',
  'TN': 'Venezia & Veneto', 'BZ': 'Venezia & Veneto',
  'TS': 'Venezia & Veneto', 'UD': 'Venezia & Veneto', 'PN': 'Venezia & Veneto', 'GO': 'Venezia & Veneto',
  'AN': 'Venezia & Veneto', 'PU': 'Venezia & Veneto', 'MC': 'Venezia & Veneto',
  'AP': 'Venezia & Veneto', 'FM': 'Venezia & Veneto',
  'BO': 'Venezia & Veneto', 'MO': 'Venezia & Veneto', 'PR': 'Venezia & Veneto',
  'RE': 'Venezia & Veneto', 'FE': 'Venezia & Veneto', 'RN': 'Venezia & Veneto',
  'FC': 'Venezia & Veneto', 'RA': 'Venezia & Veneto', 'PC': 'Venezia & Veneto',
  'GE': 'Liguria', 'SP': 'Liguria', 'SV': 'Liguria', 'IM': 'Liguria',
  'FI': 'Toscana', 'SI': 'Toscana', 'PI': 'Toscana', 'AR': 'Toscana',
  'PT': 'Toscana', 'PO': 'Toscana', 'LU': 'Toscana', 'MS': 'Toscana',
  'GR': 'Toscana', 'LI': 'Toscana',
  'PG': 'Umbria', 'TR': 'Umbria',
  'RM': 'Roma & Lazio', 'LT': 'Roma & Lazio', 'FR': 'Roma & Lazio',
  'VT': 'Roma & Lazio', 'RI': 'Roma & Lazio',
  'AQ': 'Roma & Lazio', 'PE': 'Roma & Lazio', 'CH': 'Roma & Lazio',
  'TE': 'Roma & Lazio', 'CB': 'Roma & Lazio', 'IS': 'Roma & Lazio',
  'NA': 'Amalfi Coast', 'SA': 'Amalfi Coast', 'CE': 'Amalfi Coast',
  'BN': 'Amalfi Coast', 'AV': 'Amalfi Coast',
  'BA': 'Puglia', 'TA': 'Puglia', 'FG': 'Puglia', 'LE': 'Puglia',
  'BR': 'Puglia', 'BT': 'Puglia',
  'PZ': 'Puglia', 'MT': 'Puglia', 'RC': 'Puglia', 'CZ': 'Puglia',
  'CS': 'Puglia', 'KR': 'Puglia', 'VV': 'Puglia',
  'PA': 'Sicilia', 'CT': 'Sicilia', 'ME': 'Sicilia', 'SR': 'Sicilia',
  'AG': 'Sicilia', 'TP': 'Sicilia', 'RG': 'Sicilia', 'CL': 'Sicilia', 'EN': 'Sicilia',
  'CA': 'Liguria', 'SS': 'Liguria', 'NU': 'Liguria', 'OR': 'Liguria', 'OT': 'Liguria',
}

const stripAccents = (s: string) =>
  s.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/['']/g, "'")

export function cercaComuni(
  query: string,
  maxResults = 8
): { nome: string; provincia: string; regione: string; veloZona: string }[] {
  if (!query || query.length < 2) return []
  const q = stripAccents(query.trim())
  const addZona = (c: typeof COMUNI_ITALIANI[0]) => ({
    ...c,
    veloZona: PROVINCIA_TO_VELO_ZONA[c.provincia] || 'Toscana',
  })
  const starts   = COMUNI_ITALIANI.filter(c => stripAccents(c.nome).startsWith(q)).map(addZona)
  const contains = COMUNI_ITALIANI.filter(
    c => !stripAccents(c.nome).startsWith(q) && stripAccents(c.nome).includes(q)
  ).map(addZona)
  return [...starts, ...contains].slice(0, maxResults)
}
